### PR TITLE
fix: make sure the diff is always positive

### LINKED ISSUE #92: Location time is sometimes negative
Time in location is shown with negative numbers on some devices.

### PR DESCRIPTION
**Pull request by Lenakh97**
closes #92

### CODE REVIEW

**Comment by Lenakh97** [comment]
I have tried different approaches and this is the only one that has worked for me. As far as I can see the value is always correct, it just has a '-' in front of it. The fix is verified by checking that it works on my phone, which has been showing negative numbers until this fix.

File: src/GeoLocationAge.tsx [hunk 1]
```diff
@@ -16,5 +16,5 @@ export const GeoLocationAge = ({ age }: { age: Date }) => {
 		}
 	}, [location])
 
-	return <time dateTime={age.toISOString()}>{diff}</time>
+	return <time dateTime={age.toISOString()}>{diff.replace(/^-\s*/, '')}</time>
```
Comment (coderbyheart) [inline src/GeoLocationAge.tsx]: Hehe, nice.

I think `Math.abs` is a better solution.

And this does not look like a fix, because it would just convert negative distance to positive, which is not correct.

**Comment by coderbyheart** [comment]
This seems to be cause by https://github.com/date-fns/date-fns/issues/3238

**Comment by coderbyheart** [comment]
- Remove `GeoLocationAge` and use `RelativeTime` instead
- Remove **all** usages of `intlFormatDistance()` from the code base and use `formatDistance()` from `RelativeTime`

**Comment by Lenakh97** [comment]
I removed GeoLocationAge and used RelativeTime instead. intlFormatDistance was only used once in this repo. The change I see is that we loose the 'ago' behind the time. We are also missing the 'yesterday' text and getting '16h' for example.

I can also see that the location time changes more in this version than in saga right now. Do we have any rules on when they should be updated?

Attaching a photo of localhost in this branch VS world.thingy.rocks:
Screenshot 2025-10-16 at 15 21 05

**Comment by coderbyheart** [comment]
> intlFormatDistance was only used once in this repo.

Please remove it.

**Comment by coderbyheart** [comment]
> I can also see that the location time changes more in this version than in saga right now. Do we have any rules on when they should be updated?

What does "more" mean?

**Comment by Lenakh97** [comment]
> > intlFormatDistance was only used once in this repo.
> 
> Please remove it.

It is removed!

**Comment by Lenakh97** [comment]
> > I can also see that the location time changes more in this version than in saga right now. Do we have any rules on when they should be updated?
> 
> What does "more" mean?

If you look at 'Sly 91X' in the screenshot I added the version in saga (to the right) says Wi-Fi was updated 1h ago, while in this branch is says 3s and it will count up. Same with 'single-cell': 1h VS 2m. I am passing in 'location.ts' to Relativetime so I believe it should only update when location is updated so I'm not sure why we have the differences.

**Comment by coderbyheart** [comment]
I believe this is just because the left has more recent updates to the geo location.

**Comment by coderbyheart** [comment]
I've changed the unit of the time to be distinguishable now from distance.

image
